name: turing_sales

version: 1.0.0

config-version: 2

model-paths:
  - models

target-path: target

profile: dev-bigquery

models:
  turing_sales:
    marts:
      core:
        fct_customer_orders:
          +materialized: table
    dimensions:
      +materialized: table