version: "3.9"

services:
  dbt:
    image: ghcr.io/dbt-labs/dbt-bigquery:1.7.2
    build:
      context: .
      target: dbt-bigquery
    volumes:
      - .:/usr/app/dbt
      - ~/.dbt:/root/.dbt:ro
      - ~/.google/credentials/google_credentials.json:/root/.google/credentials/google_credentials.json:ro
    command: -d run