version: "3.9"

services:
  dbt:
    image: ghcr.io/dbt-labs/dbt-bigquery:1.7.2
    build:
      context: .
      target: dbt-bigquery
    ports:
      - "8080:8080"
    volumes:
      - .:/project
      - ~/.dbt:/root/.dbt
      - ~/.google/credentials/google_credentials.json:/root/.google/credentials/google_credentials.json